config/routes.rb
Rails.application.routes.draw do
  resources :tweets
  root 'pages#show', page: 'home'
  get '/pages/:page', to: 'pages#show'

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  validates :handle, presence: true
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
      page = params[:page]
      render "pages/#{page}"
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def index
    @tweets = Tweet.all
  end

  def create
    @tweet = Tweet.new(params.require(:tweet).permit(:handle, :content))

     if @tweet.save
       redirect_to tweets_path
     else
       render :new
     end
  end

  def new
    @tweet = Tweet.new
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def show
    @tweet = Tweet.find(params[:id])
  end

  def update
    @tweet = Tweet.find(params[:id])

      if @tweet.update_attributes(params.require(:tweet).permit(:handle, :content))
        redirect_to tweets_path
      else
        render :edit
      end
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    redirect_to tweets_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsTwitter</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/tweets/edit.html.erb
<ul class="nav nav-pills">
  <li role="presentation"><%= link_to "Home", root_path%></li>
  <li role="presentation" class="active"><%= link_to "View Tweets", tweets_path%></li>
  <li role="presentation"><%= link_to "New Tweet", new_tweet_path%></li>
</ul>

<div class="jumbotron text-center">
  <h1>WDI Twitter</h1>
</div>

<%= form_for @tweet do |f| %>
  <div class="container jumbotron ">
    <div>
      <%= f.label :handle, :class => 'form-group' %>
      <br>
      <%= f.text_field :handle, :class => 'form-group', :placeholder => "Handle Name:" %>
    </div>

    <div>
      <%= f.label :content, :class => 'form-group' %>
      <br>
      <%= f.text_field :content, :class => 'form-group form-control', :placeholder => "Comment goes here:"%>
    </div>
    <hr>
    <%= f.submit "submit edit", :class => 'btn btn-success' %>
  </div>
<% end %>

app/views/tweets/index.html.erb
<ul class="nav nav-pills">
  <li role="presentation"><%= link_to "Home", root_path%></li>
  <li role="presentation" class="active"><%= link_to "View Tweets", tweets_path%></li>
  <li role="presentation"><%= link_to "New Tweet", new_tweet_path%></li>
</ul>

<div class="jumbotron text-center">
  <h1>Tweet feed</h1>
</div>


  <% @tweets.each do |tweet| %>
    <div class="panel panel-default">
      <div class="panel-heading pheading">
        <h3 class="panel-title tweet pull-left"><%= tweet.handle %></h3>
        <h3 class="panel-title tweet pull-right"><%= tweet.created_at.localtime.strftime(" %I:%M %P %b, %-d, %Y") %></h3>
      </div>
      <div class="panel-body">
        <%= tweet.content %>
        <br>
        <hr>
        <p> <%= link_to "View", tweet_path(tweet), :class => "btn btn-default"%></p>
      </div>
    </div>
  <% end %>

app/views/tweets/new.html.erb
<ul class="nav nav-pills">
  <li role="presentation"><%= link_to "Home", root_path%></li>
  <li role="presentation"><%= link_to "View Tweets", tweets_path%></li>
  <li role="presentation" class="active"><%= link_to "New Tweet", new_tweet_path%></li>
</ul>

<div class="jumbotron text-center">
  <h1>Make new tweet</h1>
</div>

<%= form_for @tweet do |f| %>
  <div class="container jumbotron ">
    <div>
      <%= f.label :handle, :class => 'form-group' %>
      <br>
      <%= f.text_field :handle, :class => 'form-group', :placeholder => "Handle Name:" %>
    </div>

    <div>
      <%= f.label :content, :class => 'form-group' %>
      <br>
      <%= f.text_field :content, :class => 'form-group form-control', :placeholder => "Comment goes here:"%>
    </div>
    <hr>
    <%= f.submit "submit tweet", :class => 'btn btn-success' %>
  </div>
<% end %>

app/views/tweets/show.html.erb
<ul class="nav nav-pills">
  <li role="presentation"><%= link_to "Home", root_path%></li>
  <li role="presentation" class="active"><%= link_to "View Tweets", tweets_path%></li>
  <li role="presentation"><%= link_to "New Tweet", new_tweet_path%></li>
</ul>

<div class="jumbotron text-center">
  <h1>WDI Twitter</h1>
</div>




<div class="panel panel-default">
  <div class="panel-heading  pheading">
    <h3 class="panel-title tweet pull-left"><%= @tweet.handle %></h3>
    <h3 class="panel-title tweet pull-right"><%= @tweet.created_at.localtime.strftime(" %I:%M %P %b, %-d, %Y") %></h3>
  </div>
  <div class="panel-body">
    <%= @tweet.content %>
    <br>
    <hr>
    <%= link_to "Edit", edit_tweet_path(@tweet), :class => "btn btn-warning" %>
    <%= link_to "Delete", tweet_path(@tweet), method: :delete, :class => "btn btn-danger", data: { confirm: "are you sure you want to delete this Tweet?"} %>
    <%= link_to "Go Back", tweets_path(@tweet), :class => "btn btn-default"%>
  </div>
</div>